spring:
  application:
    name: configuration-center
# git config server
  cloud:
      config:
        server:
          git:
            uri: https://github.com/shersfy/config-repo.git
            search-paths: /**
#            username: username
#            password: password
            
server:
  port: 8877
 
# eureka client
eureka:
  instance:
    prefer-ip-address: true
  client:
    eureka-server-d-n-s-name: 172.18.9.201
    eureka-server-port: 8899
    service-url:
      defaultZone: http://${eureka.client.eureka-server-d-n-s-name}:${eureka.client.eureka-server-port}/eureka/

# logging
logging:
  file: logs/${spring.application.name}.log
  file.max-size: 100MB
  level:
    root: info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    level: '%5p'