spring:
  application:
    name: app-onos
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.28.23.93:3306/sdn?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
# server
server:
  port: 8181
# eureka client
eureka:
  client:
    eureka-server-d-n-s-name: 172.18.9.201
    eureka-server-port: 8899
    service-url:
      defaultZone: http://${eureka.client.eureka-server-d-n-s-name}:${eureka.client.eureka-server-port}/eureka/
# logging
logging:
  file: logs/${spring.application.name}.log
  file.max-size: 100MB
  level:
    root: info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    level: '%5p'