spring:
  application:
    name: app-onos
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://172.18.9.214:3306/sdn?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 123456
# server
server:
  port: 8181
# eureka server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# logging
logging:
  file: logs/${spring.application.name}.log
  file.max-size: 100MB
  level:
    root: info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    level: '%5p'