server:
  port: 8084
spring:
  application:
    name: app-nginx-sidecar-proxy
# sidecar
sidecar:
  port: 80
  hostname: 192.168.186.128
  health-uri: http://${sidecar.hostname}:${sidecar.port}/health.json
# eureka server
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
# logging
logging:
  file: logs/${spring.application.name}.log
  file.max-size: 100MB
  level:
    root: info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    level: '%5p'