spring:
  application:
    name: xxx-app-sidecar-proxy
server:
  port: 8081
# sidecar
sidecar:
  port: 8080
  hostname: 172.18.9.195
  health-uri: http://${sidecar.hostname}:${sidecar.port}/health.json
# eureka client
eureka:
  client:
    eureka-server-d-n-s-name: 172.18.9.201
    eureka-server-port: 8899
    service-url:
      defaultZone: http://${eureka.client.eureka-server-d-n-s-name}:${eureka.client.eureka-server-port}/eureka/
# logging
logging:
  file: logs/${spring.application.name}.log
  file.max-size: 100MB
  level:
    root: info
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
    level: '%5p'